{% set version = "20200219" %}

package:
    name: backtrace
    version: {{ version }}

source:
    url: https://github.com/ianlancetaylor/libbacktrace/archive/ca0de0517f3be44fedf5a2c01cfaf6437d4cae68.zip
    sha256: 4ad4f63e5771d9d82a67d59976061f26b24677f19fbe29c54e6db7760df99031

build:
    number: 0
    skip: true  # [osx]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - zlib

test:
    commands:
        - test -f ${PREFIX}/lib/libbacktrace.a
        - test -f ${PREFIX}/lib/libbacktrace.so
        - test -f ${PREFIX}/include/backtrace.h

about:
    home: https://github.com/ianlancetaylor/libbacktrace
    license: BSD 3-clause
    summary: A C library that may be linked into a C/C++ program to produce symbolic backtraces
    license_file: LICENSE

extra:
    recipe-maintainers:
        - bluescarni
