{% set version = "20241216" %}

package:
    name: backtrace
    version: {{ version }}

source:
    url: https://github.com/ianlancetaylor/libbacktrace/archive/1db85642e3fca189cf4e076f840a45d6934b2456.zip
    sha256: 9211bb87add7ccdca625ac75dbd4e9f5726f1e99da54c4f1583d0fa21e380c9b

build:
    number: 0
    run_exports:
        - {{ pin_subpackage('backtrace', max_pin='x.x') }}
    skip: true  # [win]

requirements:
    build:
        - {{ compiler('c') }}
        - libcxx     # [osx]
        - make       # [unix]
    host:
        - zlib {{ zlib }}

test:
    commands:
        - test -f ${PREFIX}/lib/libbacktrace.a
        - test -f ${PREFIX}/lib/libbacktrace.so     # [linux]
        - test -f ${PREFIX}/lib/libbacktrace.dylib  # [osx]
        - test -f ${PREFIX}/include/backtrace.h

about:
    home: https://github.com/ianlancetaylor/libbacktrace
    dev_url: https://github.com/ianlancetaylor/libbacktrace
    doc_url: https://github.com/ianlancetaylor/libbacktrace
    summary: A C library that may be linked into a C/C++ program to produce symbolic backtraces
    description: |
        Libbacktrace is a lightweight C library for generating symbolic backtraces in C/C++ apps. 
        It supports various executable formats with DWARF debugging and is ideal for error reporting and profiling.
    license: BSD-3-Clause
    license_file: LICENSE
    license_family: BSD

extra:
    recipe-maintainers:
        - bluescarni
