{% set version = "2019.12" %}

package:
    name: backtrace
    version: {{ version }}

source:
    url: https://github.com/ianlancetaylor/libbacktrace/archive/559ab7cab4a6002124863d493bd09a376a690e76.zip
    sha256: f93a80af6bdc3e80674191ba787d0d6c81a8582d01bc093c293b5eda20c4cea7

build:
    number: 0
    skip: true  # [win or osx]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - zlib

test:
    commands:
        - test -f ${PREFIX}/lib/libbacktrace.a
        - test -f ${PREFIX}/lib/libbacktrace.so
        - test -f ${PREFIX}/include/backtrace.h

about:
    home: https://github.com/ianlancetaylor/libbacktrace
    license: BSD 3-clause
    summary: A C library that may be linked into a C/C++ program to produce symbolic backtraces
    license_file: LICENSE

extra:
    recipe-maintainers:
        - bluescarni
