travis:
  secure:
    BINSTAR_TOKEN: HNDAN7QS7lBA3AA23WmX2QGfvZIlQMZY6103wlCldPNVLMqOQ4Q7x+L+a3SAcHGHC+Ttuu6YivWIJbTX1u1y44QNV4uVQtBQK3IpBfqMD/9ZY3wzACL44MZxxrhZaQuCI0KtWaBDRE/6QgmM0APDX2PgeNZgI6jZKFV6b8jaSKT5O/BdDz3RKsIe2qHkHgkzPJVATBMc54Pl6zXddHB+Ko/aekvhEm+CLr1aeNhws3rOZdwqywJWbkMPxYfXNsI+qSBmn3Rea9Li8Yvgn0tiV0EK1pzEHX+FWF4asUiSVzFU6Le4ZQu8mqmb4S6tWvvCcu7WpbTbsT69sGnYrGsP44of7xVygiWRDQJv+tb+nHQUgFQg65p5WfOzWp/u+cFVXJu7uWvOEL6WGyxoZi+5xwv335gShDRrFwnBn88Sdl5p4sB9bMpdUa69oYX90rl8aJ5+nd+9ogdTRQgFmzq7wtTg5d3z/jTCOU78UskQi3M9DJ0ZxrVEEehzR9MBSIE9r7lYp625sMkOFzQef5enX4d3qk/W4Cl9/qgj9SgbKDGYJcyQX2ozTeOmdc9t38LMbNvv6IbKL47XL0v/JM3m9x3fuHZ+GZsTTaJvHXnsDAqqZS1Mo/O2fLU65lRG7zkHr8RLa8PcWDfnwO2B7hJK2B5KxCPBv4aFrmjii/WdYN4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
